services:
  alloy_agent:
    description: "Grafana Alloy Agent"
    args: "run..."
    binaries: ["alloy_agent"]
    templates: ["alloy_agent"]
    requires: []

  loki_exporter:
    description: "Extra log pipeline / exporter for Loki"
    args: "run..."
    binaries: []
    templates: ["loki_exporter"]
    requires: ["alloy_agent"]